### ISSUE TITLE
VkLayer_khronos_profiles.json.in doesn't have env vars listed

### ISSUE THREAD

**Issue by davidlunarg** [KhronosGroup/Vulkan-Profiles#113]
Many of the settings in the profile layer can be set via an envirorment variable, for example VK_KHRONOS_PROFILES_PROFILE_FILE.

The env variables that can be used to control the settings are not listed in VkLayer_khronos_profiles.json.in. As we switch to generating layer documentation automagically using vkconfig output, these env vars won't be listed in the documentation.

**Comment by christophe-lunarg** [comment]
This is on purpose, we don't need environment variable names because the name can be generated from the setting key.

So if the key is "profile_file" then the namespace is given by the layer name.

**Comment by christophe-lunarg** [comment]
If we want to override the environment variable name, when the "env" can be used but it's not recommanded. We had to have "env" because our naming is sometimes inconsistent.

The generated ENV variables name goal is to ensure this consistency.

**Comment by mark-lunarg** [comment]
Does this mean that neither the environment variables nor the setting keys show up in the autogenerated docs?  Also, it not including environment variables because they are not recommended seems inconsistent with the guidance we received in the other repos?

**Comment by christophe-lunarg** [comment]
No, the environment variables should be documented it's just the names should be generated instead from the setting key and or specified if the env variables doesn't follow the consistency convension.
