### ISSUE TITLE
Clarify the message when an extension is missing but a structure is set

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-Profiles#120]
When an extension is missing we get that kind of message:
```
PROFILES ERROR: Profile sets variables for structs provided by VK_EXT_descriptor_indexing, but VK_EXT_descriptor_indexing is not enabled by the profile.
PROFILES ERROR: Profile sets variables for structs provided by VK_EXT_descriptor_indexing, but VK_EXT_descriptor_indexing is not enabled by the profile.
```
There is two message but it's not duplicate, it's because we have VkPhysicalDeviceDescriptorIndexingFeaturesEXT and VkPhysicalDeviceDescriptorIndexingPropertiesEXT

But we could print the structure name:
"Profile requires VkPhysicalDeviceDescriptorIndexingFeaturesEXT capabilities, but VK_EXT_descriptor_indexing is not required by the profile. +WHAT THE BEHAVIOR THEN+"

For SDK 1.3.204.1 release.

**Comment by ziga-lunarg** [comment]
Closed by #125
