### ISSUE TITLE
vulkan11requirements references VkPhysicalDeviceVulkan11Features

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Profiles#20]
The `vulkan11requirements` key in `VK_KHR_roadmap_2022.json` references the struct `VkPhysicalDeviceVulkan11Features`. However, that structure is only available in Vulkan 1.2 and later.

https://github.com/KhronosGroup/Vulkan-Profiles/blob/741df065c073d48174ea9d00546b21e95ddd1ded/profiles/VP_KHR_roadmap_2022.json#L13

**Comment by christophe-lunarg** [comment]
The VK_KHR_roadmap_2022 profile is written against Vulkan 1.3 so it can use any of the Vulkan 1.3 structures.

The capabilities organize the features requirements per Vulkan version but it's arbitrary and purely a way to organize them. So everything could have been in the same bloc when it seems easier to read the file to state when (per version) the features where introduced.

Thanks for contributing!
