### ISSUE TITLE
Figure out something so that GPUInfo reports with profile applied are clearly identified

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-Profiles#203]
When using Vulkan Configurator with the Vulkan Profiles layer:
![image](https://user-images.githubusercontent.com/62888873/168119041-96338fd5-2a6a-4546-88cc-5dfad7f40f62.png)

The profile is applied on the drivers to Vulkan Caps Viewer read the capabilities with the profiles applied:
![image](https://user-images.githubusercontent.com/62888873/168120431-a90f6d0c-ef46-450d-a812-e9c4fdeae748.png)

This is probably fine locally but really we should avoid to polute GPUInfo database, so somehow if such report are uploaded, we should figure something so that those reports are clearly identified.

We thought about adding to the deviceName, the profile name applied.

**Comment by christophe-lunarg** [comment]
Any opinion @SaschaWillems?

**Comment by SaschaWillems** [comment]
Good point. I was wondering about this myself. As you noticed, you can easily generate and (sadly) upload those reports. 

As of now it doesn't look like there's a way to identify that data has been injected using the profiles layer, and that's what I'd need to tell the user "you're running with a profile enabled - upload disabled".

Maybe `VK_EXT_tooling_info` could be used for that, though that's not widely supported. Or the layer could inject an instance extension when active, which could be easily checked.

**Comment by christophe-lunarg** [comment]
Ah, interesting point. I didn't thought about preventing the upload.

I double checked building your Vulkan samples, what happened? Oo), I could double check that when the Profiles layer, it's reported by vkGetPhysicalDeviceToolProperties.

This is how we implemented it:
```
VKAPI_ATTR VkResult VKAPI_CALL GetPhysicalDeviceToolPropertiesEXT(VkPhysicalDevice physicalDevice, uint32_t *pToolCount,
                                                                  VkPhysicalDeviceToolPropertiesEXT *pToolProperties) {
    LogMessage(DEBUG_REPORT_DEBUG_BIT, "GetPhysicalDeviceToolPropertiesEXT\n");
    LogFlush();

    std::stringstream version_stream;
    version_stream << kVersionProfilesMajor << "." << kVersionProfilesMinor << "." << kVersionProfilesPatch;
    std::string version_string(version_stream.str());

    static VkPhysicalDeviceToolPropertiesEXT profiles_layer_tool_props = {};
    profiles_layer_tool_props.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TOOL_PROPERTIES_EXT;
    profiles_layer_tool_props.pNext = nullptr;
    strcpy(profiles_layer_tool_props.name, kLayerProperties[0].description);
    strcpy(profiles_layer_tool_props.version, version_string.c_str());
    profiles_layer_tool_props.purposes = VK_TOOL_PURPOSE_MODIFYING_FEATURES_BIT_EXT;
    strcpy(profiles_layer_tool_props.description, kLayerProperties[0].description);
    strcpy(profiles_layer_tool_props.layer, kLayerProperties[0].layerName);

    auto original_pToolProperties = pToolProperties;
    if (pToolProperties != nullptr) {
        *pToolProperties = profiles_layer_tool_props;
        pToolProperties = ((*pToolCount > 1) ? &pToolProperties[1] : nullptr);
        (*pToolCount)--;
    }

    VkLayerInstanceDispatchTable *pInstanceTable = instance_dispatch_table(physicalDevice);
    VkResult result = pInstanceTable->GetPhysicalDeviceToolPropertiesEXT(physicalDevice, pToolCount, pToolProperties);

    if (original_pToolProperties != nullptr) {
        pToolProperties = original_pToolProperties;
    }

    (*pToolCount)++;

    return result;
}
```

So you should be able to modify vulkancapsviewer checking this.

I still find it pretty useful to be able to open vulkancapsviewer with a profile applied, it kind of make it a profile visualiser. So I think only the upload should be prevented.

Would that be a good enough solution in your opinion ?

**Comment by christophe-lunarg** [comment]
Ok then closing this issue. Thanks !
