### ISSUE TITLE
Endless loop / crash when querying profile support on llvmpipe

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Profiles#207]
With recent Vulkan Hardware Capability viewers supporting profiles, I've been getting several reports that the app crashes on Linux systems with recent Mesa drivers:
* https://github.com/SaschaWillems/VulkanCapsViewer/issues/142
* https://github.com/SaschaWillems/VulkanCapsViewer/issues/143
* https://github.com/SaschaWillems/VulkanCapsViewer/issues/145

The application segfaults when trying to read support for the VP_LUNARG_desktop_portability_2021 profile.

After some debugging it looks like a problem with llvmpipe devices, which is a software implementation that is installed with recent Mesa drivers.

The problem is caused by a loop in the format checking part of the profiles library: https://github.com/KhronosGroup/Vulkan-Profiles/blob/master/library/include/vulkan/vulkan_profiles.hpp#L8276

On the llvmpipe device this part either segfaults (in release mode), which crashes the whole app, or (in debug mode) is stuck in an endless loop, as the `p` never seems to get a valid pointer.

To rule out a problem with how profiles are implemented in the app, I wrote a small standalone repocase for Linux that displays the exact same problem when running on a Linux system with recent Mesa drivers that also install the llvmpipe device: https://github.com/SaschaWillems/VulkanProfiles-TestCase

I'm not sure if this is something that can be fixed in the profiles library, or if this is something that Mesa needs to fix.

A user of my app has opened an issue with Mesa, but no response yet: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6451

**Comment by dpanter** [comment]
The application works when enabling the validation layer. I've updated vulkancapsviewer bugreport 143 mentioned above with logs and fresh system specs, again here for convenience. [Specs](https://termbin.com/qg8m) and [log](https://pastebin.com/YX3Sgw5S)

**Comment by SaschaWillems** [comment]
As @dpanter noted in https://gitlab.freedesktop.org/mesa/mesa/-/issues/6451, this Issue was fixed with a recent mesa release.
