### ISSUE TITLE
Path to JSON Schema gives a HTTP 404 error

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/Vulkan-Profiles#21]
The URL https://schema.khronos.org/vulkan/profiles-1.3.204.json# responds with a HTTP 404 status code.

https://github.com/KhronosGroup/Vulkan-Profiles/blob/741df065c073d48174ea9d00546b21e95ddd1ded/profiles/VP_KHR_roadmap_2022.json#L2

**Comment by KhronosWebservices** [comment]
If the URL is accuate, some one will need to send @KhronosWebservices  the schema files to upload to the Khronos CDN.

**Comment by christophe-lunarg** [comment]
In the meantime, you will be able to find the up to date schema here: https://github.com/KhronosGroup/Vulkan-Profiles/blob/master/schema/profile_schema.json
