### ISSUE TITLE
Incorrect Roadmap 2022 conditions 

### ISSUE THREAD

**Issue by r-potter** [KhronosGroup/Vulkan-Profiles#226]
The Xclipse 920 version of the Samsung S22 fails to correctly validate against the Roadmap 2022 profile for the following reasons, all of which I believe are library bugs:

```
Profiles: Unsupported feature condition: VkPhysicalDeviceVulkan12Features::vulkanMemoryModelAvailabilityVisibilityChains == VK_TRUE
Profiles: Unsupported properties condition: VkPhysicalDeviceProperties2KHR::properties.limits.bufferImageGranularity % 4096 == 0
Profiles: Unsupported properties condition: VkPhysicalDeviceVulkan11Properties::subgroupSize == 4
```

* `vulkanMemoryModelAvailabilityVisibilityChains` was erroneously introduced as a Vulkan 1.3 mandatory feature, and later removed. 
* We report 1 for `bufferImageGranularity`, indicating no granularity requirements. Additionally, I believe this test is incorrect, and granularities less than 4096 should be accepted
* We report a subgroupSize of 64. I believe that the test here should have been "at least 4" not "exactly 4"

**Comment by christophe-lunarg** [comment]
I need more to do more investigation for `bufferImageGranularity`, it's probably hard to resolve because it implies a dependency mechanisium which currently doesn't exist and is not express in `vk.xml.`..

**Comment by christophe-lunarg** [comment]
@r-potter looking at this more closely, I realised the implementation of the `mul` limittype for integer was just wrong.
I created a PR: https://github.com/KhronosGroup/Vulkan-Profiles/pull/235 which will complete the fixes.

Thanks for reporting!
