### ISSUE TITLE
Android failure in vpGetPhysicalDeviceProfileSupport

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-Profiles#262]
**Vulkan-Profiles** unit tests fail on a **Pixel 6** device:
```
INFO: starting com.example.VulkanProfilesLayerTests on Pixel_6-1B211FDF60004H - see the build artifact vulkantest-debug.log for more details on the device commands used to install and execute
INFO: installing package /home/papillo/work/KhronosGroup/Vulkan-Profiles/android-build/apk/out/VulkanProfilesLayerTests.apk on Pixel_6-1B211FDF60004H
INFO: Pixel_6-1B211FDF60004H: starting com.example.VulkanProfilesLayerTests
INFO: Pixel_6-1B211FDF60004H: pulling generated result files...
INFO: Pixel_6-1B211FDF60004H: PASS: 34 tests pass
INFO: ---- testing VpLibrary_test_api_create_device_android on all devices...
INFO: starting com.example.VpLibrary_test_api_create_device_android on Pixel_6-1B211FDF60004H - see the build artifact vulkantest-debug.log for more details on the device commands used to install and execute
INFO: installing package /home/papillo/work/KhronosGroup/Vulkan-Profiles/android-build/apk/out/VpLibrary_test_api_create_device_android.apk on Pixel_6-1B211FDF60004H
INFO: Pixel_6-1B211FDF60004H: starting com.example.VpLibrary_test_api_create_device_android
INFO: Pixel_6-1B211FDF60004H: pulling generated result files...
ERROR: [ RUN      ] library_api.vpGetPhysicalDeviceProfileSupport
ERROR: /home/papillo/work/KhronosGroup/Vulkan-Profiles/library/test/test_api_create_device_android.cpp:293: Failure
ERROR: Expected equality of these values:
ERROR:   1U
ERROR:     Which is: 1
ERROR:   supported
ERROR:     Which is: 0
ERROR: [  FAILED  ] library_api.vpGetPhysicalDeviceProfileSupport (3 ms)
ERROR: Pixel_6-1B211FDF60004H: FAIL: 1 test pass, 1 test fail
ERROR: FAIL during test after 55.10 seconds (55.10 seconds) with Pixel_6-1B211FDF60004H: VpLibrary_test_api_create_device_android: 1 test pass, 1 test fail
INFO: Test run complete after 3.53 minutes (211.93 seconds)
```

**Comment by christophe-lunarg** [comment]
@lunarpapillo, could you give me a little bit of context? 
Was it the first time you tried to run the unit test onto it? Did it use to pass? Do we have a revision when the issue started to appear?

Was it due to an update of the Android?

**Comment by lunarpapillo** [comment]
> Was it the first time you tried to run the unit test onto it? Did it use to pass? Do we have a revision when the issue started to appear?

This was the first time the test was attempted on a **Pixel 6** device.  We're just now preparing to add such a device to CI.

> Was it due to an update of the Android? 

Possibly.  I believe the **Pixel 6** is the only device we have running **Android 12**.

> Would it be possible for you to upload a report on GPUinfo.org (https://vulkan.gpuinfo.org/download.php) so that I have an idea about what's possibly is going wrong?

Strangely, the app reported **Device is already present in the database**, but searching vulkan.gpuinfo.org for **Pixel 6** failed to find it.  With a little hand-munging, I was able to find the existing record: https://vulkan.gpuinfo.org/displayreport.php?id=12851

**Comment by lunarpapillo** [comment]
I just identified a bug in the test script; apparently this test has been failing on the **Galaxy S10** and the **Pixel 3**, but no one noticed because the test script would only report failure if the *last* APK executed showed a failure.  I have a fix.

Here is the failure on **Galaxy S10**: http://erusea:8080/job/VulkanProfiles/2036/BITS=64,BUILD_MODE=Release,label=Linux-Android/console
```
ERROR: [ RUN      ] library_api.vpGetPhysicalDeviceProfileSupport
ERROR: /home/lunarg/.jenkins/workspace/VulkanProfiles/64-bit/Release/VulkanProfiles/library/test/test_api_create_device_android.cpp:293: Failure
ERROR: Expected equality of these values:
ERROR:   1U
ERROR:     Which is: 1
ERROR:   supported
ERROR:     Which is: 0
ERROR: [  FAILED  ] library_api.vpGetPhysicalDeviceProfileSupport (21 ms)
ERROR: GalaxyS10-R28M31RTPWK: FAIL: 1 test pass, 1 test fail
```

**Comment by christophe-lunarg** [comment]
This was resolved on master branch
