### ISSUE TITLE
Missing generated header files

### ISSUE THREAD

**Issue by TheLavaBlock** [KhronosGroup/Vulkan-Profiles#301]
Hello folks,

Since #300 removed the generated header files, what is the recommended way to use the profiles in a project if you don't want to use the Vulkan SDK directly? It was very easy to include the repository in a project before, you didn't even need CMake or Python to do it.

I understand that it removes conflicts when merging, but it definitely makes direct use more difficult. Unfortunately, I can't see any benefit there at the moment. Would be very pleased to have again a simple way to do this and am curious what a solution to this might look like.

Thank you for the great work on this project. :+1:

**Comment by christophe-lunarg** [comment]
Is it particularly difficult for you to build this repository?

**Comment by christophe-lunarg** [comment]
Looking at https://github.com/liblava/liblava/blob/master/CMakeLists.txt, I think you should inspire yourself to our use to CMake FetchContent to build the Profiles repository whie configurating your project :
https://github.com/KhronosGroup/Vulkan-Profiles/blob/master/CMakeLists.txt

**Comment by TheLavaBlock** [comment]
Thank you for your answer and the hints for integration.

However, at the moment it is too much hassle for me with CMake and the corresponding externals to generate the header files myself.

**Comment by SaschaWillems** [comment]
Just noticed this too. For the Vulkan Hardware Capability Viewer I had a script that downloaded the generated files from this repo, which is no longer possible. Just being able to download those files was very convenient.
