### ISSUE TITLE
SIMULATE_FORMATS_BIT with VK_KHR_format_feature_flags2

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-Profiles#337]
If my `profile.json` file looks like

```json
"VK_FORMAT_B8G8R8A8_UNORM": {
                    "VkFormatProperties": {
                        "linearTilingFeatures": [
                            "VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT",
                        ],
                        "optimalTilingFeatures": [
                            "VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT",
                        ],
                        "bufferFeatures": []
                    }
                },
 ```
 
 but my profile also supports Vulkan 1.3 or `VK_KHR_format_feature_flags2` (which is an unique extension because if it is exposed, it has to be supported, no enabling needed)
 
 I am finding that calling 
 
 ```cpp
VkFormatProperties3KHR fmt_props_3;
VkFormatProperties2 fmt_props_2;
fmt_props_2.pNext = &fmt_props_3;
vkGetPhysicalDeviceFormatProperties2(physical_device, format, &fmt_props_2);
```

Will not return `VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_BIT` like I would expect it too

-----

I see 2 ways around this

1. Force everyone to duplicate both `VkFormatProperties` and `VkFormatProperties3`, and have tooling to validate when it is forgotten
2. Have `JsonLoader::GetFormat` have some logic to make sure `profile_properties_3` and `profile_properties` have the same union

I like number 2, there is already CTS test to make sure all implementation have the same union of formats for both

> The bits reported in **linearTilingFeatures**, **optimalTilingFeatures** and **bufferFeatures** must include the bits reported in the corresponding fields of **VkFormatProperties2::formatProperties**.

**Comment by spencer-lunarg** [comment]
for sake of unblocking anyone else with this issue by chance, this script will duplicate it over 

```python
import json

INPUT = 'profile.json'
OUTPUT = 'new_profile.json'

with open(INPUT, 'r') as file:
    data = json.load(file)

oldFormats = data['capabilities']['device']['formats']
newFormats = {}

for format in oldFormats:
    newFormats[format] = oldFormats[format]
    newFormats[format]['VkFormatProperties3'] = dict()
    newFormats[format]['VkFormatProperties3']['linearTilingFeatures'] = []
    newFormats[format]['VkFormatProperties3']['optimalTilingFeatures'] = []
    newFormats[format]['VkFormatProperties3']['bufferFeatures'] = []
    for feature in oldFormats[format]['VkFormatProperties']['linearTilingFeatures']:
        newFormats[format]['VkFormatProperties3']['linearTilingFeatures'].append('VK_FORMAT_FEATURE_2_' + feature[18:])
    for feature in oldFormats[format]['VkFormatProperties']['optimalTilingFeatures']:
        newFormats[format]['VkFormatProperties3']['optimalTilingFeatures'].append('VK_FORMAT_FEATURE_2_' + feature[18:])
    for feature in oldFormats[format]['VkFormatProperties']['bufferFeatures']:
        newFormats[format]['VkFormatProperties3']['bufferFeatures'].append('VK_FORMAT_FEATURE_2_' + feature[18:])

data['capabilities']['device']['formats'] = newFormats

with open(OUTPUT, 'w') as file:
    json.dump(data, file, indent=4)
```

**Comment by christophe-lunarg** [comment]
Hi,

So fundamentally, to be sure I understand what you want, you would like that the user could set the format properties to with `VkFormatProperties` in the profiles and get these values with `VkFormatProperties3` with the API? 

I think that makes sense, I'll add this and I think it should not be too hard to do.
