### ISSUE TITLE
VkPhysicalDeviceVulkan13Properties TexelAlignment features not modified

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-Profiles#352]
in `JsonLoader::GetStruct(const Json::Value &parent, VkPhysicalDeviceVulkan13Properties *dest)` I noticed it has

```cpp
GET_VALUE_WARN(member, storageTexelBufferOffsetAlignmentBytes, false, WarnIfLesser);
GET_VALUE_WARN(member, storageTexelBufferOffsetSingleTexelAlignment, true, WarnIfNotEqualBool);
GET_VALUE_WARN(member, uniformTexelBufferOffsetAlignmentBytes, false, WarnIfLesser);
GET_VALUE_WARN(member, uniformTexelBufferOffsetSingleTexelAlignment, true, WarnIfNotEqualBool);
```

why are `storageTexelBufferOffsetSingleTexelAlignment` and `uniformTexelBufferOffsetSingleTexelAlignment` set as "not modified"? 

I found nothing in the spec that makes these two bool special

**Comment by christophe-lunarg** [comment]
It's because in `vk.xml` `storageTexelBufferOffsetSingleTexelAlignment` and `uniformTexelBufferOffsetSingleTexelAlignment` have the limitype. `limittype="exact"`.

I guess that goes like the `pointClippingBehavior`, it's a hardware behavior, we can't just chose the value but maybe this is arguable.

**Comment by spencer-lunarg** [comment]
So this goes back for me wanting to use profiles like the old DevSim system.

but you are right, if this is for hardware specific stuff, then the only people who need this would most likely be running with a MockICD driver... which means this could be set there probably

**Comment by spencer-lunarg** [comment]
Well the "idea" of DevSim was to allow your application to run as it was on another device... I guess the level of "simulation" expected is arguable, I guess I didn't mentally group properties into a "its a hardware behavior" or not

Like once you use any different properties/extension value, might as well open the flood gate and try to simulate all the properties/extensions

**Comment by christophe-lunarg** [comment]
That the same idea for the Profiles layer. We simulate by clamping the capabilities of the device, devsim or the profiles never emulated any capabilities...

**Comment by spencer-lunarg** [comment]
> devsim or the profiles never emulated any capabilities.

I think there is a LOT of overloaded terminology with all this stuff and I am mixing things up

currently `storageTexelBufferOffsetAlignmentBytes` gets "modified" ("emulated"/"stimulate") from the profile layers, but `storageTexelBufferOffsetSingleTexelAlignment` doesn't

> like the old DevSim system

From what I use to read about DevSim, I just **assumed** it would let me override all the different values/properties/extensions "exposed" from another device
