### ISSUE TITLE
Add installation code

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Profiles#372]
On Windows there are currently no install targets.

Here are all the files that need to be installed:

- [x] Bin\VkLayer_khronos_profiles.dll
- [x] Bin\VkLayer_khronos_profiles.json
- [x] Config\VK_LAYER_KHRONOS_profiles\VP_ANDROID_baseline_2021.json
- [x] Config\VK_LAYER_KHRONOS_profiles\VP_ANDROID_baseline_2022.json
- [x] Config\VK_LAYER_KHRONOS_profiles\VP_KHR_roadmap_2022.json
- [x] Config\VK_LAYER_KHRONOS_profiles\VP_LUNARG_desktop_baseline_2022.json
- [x] Config\VK_LAYER_KHRONOS_profiles\VP_LUNARG_desktop_baseline_2023.json
- [x] Config\VK_LAYER_KHRONOS_profiles\VP_LUNARG_desktop_portability_2022.json
- [x] share\vulkan\registry\gen_profiles_file.py
- [x] share\vulkan\registry\gen_profiles_solution.py
- [x] share\vulkan\registry\profiles-0.8-latest.json
- [x] include/vulkan/vulkan_profiles.hpp

vulkan_profiles.h and vulkan_profiles.hpp should NOT be included!

**Comment by juan-lunarg** [comment]
+ @christophe-lunarg & @ziga-lunarg to double check these are the files we want installed

**Comment by ziga-lunarg** [comment]
I think this is good, but @christophe-lunarg should confirm

**Comment by christophe-lunarg** [comment]
We don't want to install "Include\vulkan\vulkan_profiles.h": C:\j\msdk\build\Vulkan-Profiles\repo\library\include\vulkan\vulkan_profiles.h and it shuld not be part of the SDK. I said it multiple times in the past but it was not taking into account.

The res is correct I believe.

**Comment by juan-lunarg** [comment]
Latest PR installs the remaining json and python files based on the requirements outline above

**Comment by christophe-lunarg** [comment]
`vulkan_profiles.hpp` should be included! Not `vulkan_profiles.h`

**Comment by juan-lunarg** [comment]
Just added installation for `vulkan_profiles.hpp`
