### ISSUE TITLE
Windows install target doesn't package everything to the traditional SDK locations

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-Profiles#385]
## Configuration Files
The **Windows SDK** has traditionally shipped the **Vulkan-Profiles** configuration files in `Config\VK_LAYER_KHRONOS_profiles\`, e.g.:
```
Config\VK_LAYER_KHRONOS_profiles\VP_ANDROID_baseline_2021.json
Config\VK_LAYER_KHRONOS_profiles\VP_ANDROID_baseline_2022.json
Config\VK_LAYER_KHRONOS_profiles\VP_KHR_roadmap_2022.json
Config\VK_LAYER_KHRONOS_profiles\VP_LUNARG_desktop_baseline_2022.json
Config\VK_LAYER_KHRONOS_profiles\VP_LUNARG_desktop_portability_2022.json
```

But when the `install` target was added for Windows, those files started to appear instead in `share\vulkan\config\VK_LAYER_KHRONOS_PROFILES`.

Either the Windows install target should put these files into a top-level `Config` directory, or the SDK packaging should move them to `share\vulkan\config\.  (The latter could be a breaking change for SDK users, so we should consider this carefully if this is the intended plan.)

## Library Files
The `install` target is also shipping `bin\VkLayer_khronos_profiles.lib`, which provokes issues:
- We've never shipped a layer `.lib` file (for any layer) before.
- The `.lib` files we are shipping are all in the `Lib\` directory.

We should do one of:
- remove the `bin\VkLayer_khronos_profiles.lib` from the `install` target
- move `bin\VkLayer_khronos_profiles.lib` to `lib\VkLayer_khronos_profiles.lib`, and add `.lib` files to the SDK for all the other layers we package

**Comment by juan-lunarg** [comment]
> But when the install target was added for Windows, those files started to appear instead in share\vulkan\config\VK_LAYER_KHRONOS_PROFILES.

I'll defer to @christophe-lunarg

> remove the bin\VkLayer_khronos_profiles.lib from the install target

We should remove the `VkLayer_khronos_profiles.lib` it's an artifact I've been meaning to get to and shouldn't be installed. Similar to the vulkan extension layer.

**Comment by lunarpapillo** [comment]
I found one more with my next SDK build attempt: http://erusea:8080/view/Manual/job/manual-sdk/516/console
```
        WARNING: generated BOM C:\j\msdk\vulkantest-results\bom\qt-repo-BOM.txt is missing entries from reference BOM C:\j\msdk\build\Vulkan-SDK-Packaging\repo\SDK_creation\Windows\qt-repo-BOM.txt:
        - CoreSDK,Include\vulkan\vulkan_profiles.h
```
It seems like the `install` target includes `include\vulkan\vulkan_profiles.hpp`, but does not provide `include\vulkan\vulkan_profiles.h`, which used to come out of `library\include\vulkan\vulkan_profiles.h`...

This should be adjusted in the `install` target.

**Comment by juan-lunarg** [comment]
> It seems like the `install` target includes `include\vulkan\vulkan_profiles.hpp`, but does not provide `include\vulkan\vulkan_profiles.h`, which used to come out of `library\include\vulkan\vulkan_profiles.h`...

@christophe-lunarg made a comment about that one specifically.

" We don't want to install "Include\vulkan\vulkan_profiles.h": C:\j\msdk\build\Vulkan-Profiles\repo\library\include\vulkan\vulkan_profiles.h and it shuld not be part of the SDK. I said it multiple times in the past but it was not taking into account."

https://github.com/KhronosGroup/Vulkan-Profiles/issues/372#issuecomment-1456240325

**Comment by lunarpapillo** [comment]
> We don't want to install "Include\vulkan\vulkan_profiles.h": C:\j\msdk\build\Vulkan-Profiles\repo\library\include\vulkan\vulkan_profiles.h and it shuld not be part of the SDK.

It's been part of the SDK for a long time.  Removing it now is dangerous because it could break users.  This should be discussed in the SDK meetings to ensure that removing it is better than leaving it in, and to ensure that proper Release Notes are written (anything removed needs to be mentioned in release notes).

**Comment by christophe-lunarg** [comment]
This issue is fixed in the Beta SDK 243.

**Comment by juan-lunarg** [comment]
The CMake hasn't been fixed. Currently the SDK has to patch the installation behavior of vulkan-profiles.
