### ISSUE TITLE
Release 1.3.251 profiles

### ISSUE THREAD

**Issue by kusma** [KhronosGroup/Vulkan-Profiles#437]
To avoid warnings with JSON validation, we need the JSON schemas for Vulkan 1.3.251 to be published for Mesa. We're using the profiles to document the features we need for our different performance profiles, and we're now using `EXT_dynamic_rendering_unused_attachments`, which was released in the Vulkan 1.3.251 spec.

**Comment by christophe-lunarg** [comment]
This issue is fixed by
https://github.com/KhronosGroup/Vulkan-Profiles/pull/438
and
https://github.com/KhronosGroup/Khronos-Schemas/pull/53
