### ISSUE TITLE
Vulkan profile validation for an implementation

### ISSUE THREAD

**Issue by llandwerlin-intel** [KhronosGroup/Vulkan-Profiles#460]
I'm looking for a tool that can tell me whether a given implementation supports a vulkan profile.

And if not print out the missing features/properties.

Is there such a thing?

**Comment by christophe-lunarg** [comment]
Hi,

You can use the [Profiles API library](https://vulkan.lunarg.com/doc/sdk/1.3.250.1/windows/profiles_api_library.html), by generating a version of the library using the `gen_profiles_solution.py` python script shipping in the Vulkan SDK (share/vulkan/registry in the Windows SDK).

You can see how to use it in the slides of this presentation: https://www.lunarg.com/wp-content/uploads/2023/02/Creating-Vulkan-Profiles-VULFEB2023.pdf

Thanks!
