### ISSUE TITLE
Fix unit tests on macOS

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-Profiles#5]

**Comment by richard-lunarg** [comment]
Latest attempt:
The following tests FAILED:
	  3 - VpLibrary_test_api_create_device_header_only (Failed)
	  4 - VpLibrary_test_api_create_device_with_source (Failed)
	  6 - VpLibrary_test_profile_support (Failed)
	  7 - VpLibrary_test_profile_examples (Failed)
	 15 - VkLayer_tests (SEGFAULT)
	 16 - VkLayer_tests_capabilities (SEGFAULT)
Errors while running CTest
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/7935777/LastTest.log)

**Comment by richard-lunarg** [comment]
Latest run this morning. Down to 4 failures on macOS with M1. Intel Mac still has 7 errors, will add that to a separate comment.
The following tests FAILED:
	  6 - VpLibrary_test_profile_support (Failed)
	 15 - VkLayer_tests (SEGFAULT)
	 16 - VkLayer_tests_promoted (SEGFAULT)
	 17 - VkLayer_tests_capabilities (SEGFAULT)
Errors while running CTest
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/7943859/LastTest.log)

**Comment by richard-lunarg** [comment]
Intel Mac failures:
The following tests FAILED:
	  3 - VpLibrary_test_api_create_device_header_only (Failed)
	  4 - VpLibrary_test_api_create_device_with_source (Failed)
	  6 - VpLibrary_test_profile_support (Failed)
	  7 - VpLibrary_test_profile_examples (Failed)
	 15 - VkLayer_tests (SEGFAULT)
	 16 - VkLayer_tests_promoted (SEGFAULT)
	 17 - VkLayer_tests_capabilities (SEGFAULT)
Errors while running CTest
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/7943874/LastTest.log)

**Comment by christophe-lunarg** [comment]
@richard-lunarg, I think the SEGFAULT issue will require to stepping into the code...

**Comment by richard-lunarg** [comment]
Intel is down to 6 failures, with some overlap with M1.
The following tests FAILED:
	  3 - VpLibrary_test_api_create_device_header_only (Failed)
	  4 - VpLibrary_test_api_create_device_with_source (Failed)
	  6 - VpLibrary_test_profile_examples (Failed)
	 14 - VkLayer_tests (SEGFAULT)
	 15 - VkLayer_tests_promoted (SEGFAULT)
	 16 - VkLayer_tests_capabilities (SEGFAULT)
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/7944281/LastTest.log)

**Comment by richard-lunarg** [comment]
Down to 4 on Intel.
The following tests FAILED:
	  1 - VpLibrary_test_api_reflection_header_only (Failed)
	  2 - VpLibrary_test_api_reflection_with_source (Failed)
	 14 - VkLayer_tests (SEGFAULT)
	 16 - VkLayer_tests_capabilities (SEGFAULT)
Errors while running CTest
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/7944423/LastTest.log)

**Comment by richard-lunarg** [comment]
On Apple Silicon, we are down to 4 tests failing, but no SEGFAULT's!
The following tests FAILED:
	 15 - VkLayer_tests (Subprocess aborted)
	 16 - VkLayer_tests_promoted (Subprocess aborted)
	 18 - VkLayer_tests_desktop_portability (Subprocess aborted)
	 19 - VkLayer_tests_capabilities (Subprocess aborted)
Errors while running CTest
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/7951726/LastTest.log)

**Comment by richard-lunarg** [comment]
With the latest branch, layer-fix-macos, I'm still getting 4 or 5 failures... yes, it varies randomly. The 5 failure tests are:

75% tests passed, 5 tests failed out of 20

Total Test time (real) =   0.60 sec

The following tests FAILED:
	 15 - VkLayer_tests (Subprocess aborted)
	 16 - VkLayer_tests_promoted (Subprocess aborted)
	 17 - VkLayer_tests_mechanism (Subprocess aborted)
	 18 - VkLayer_tests_desktop_portability (Subprocess aborted)
	 19 - VkLayer_tests_capabilities (Subprocess aborted)
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/7952576/LastTest.log)

Sometimes however, Test #17 passes!

**Comment by richard-lunarg** [comment]
All unit tests are passing reliably on Apple Silicon. However, Intel tests still fail sporadically. 
15, 17, 18, 19. Which tests fail appears to be random.

17, 18, & 19 when they fail it is with SEGFAULT

Here is a log where all four fail (15, 17, 18, 19)
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/7954203/LastTest.log)

**Comment by richard-lunarg** [comment]
I can crash the layer with vkconfig easily. Here's a stack trace with line numbers:

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libVkLayer_khronos_validation.dylib	0x00000001220554c4 DispatchGetPhysicalDeviceQueueFamilyProperties(VkPhysicalDevice_T*, unsigned int*, VkQueueFamilyProperties*) + 68 (layer_chassis_dispatch.cpp:1374)
1   libVkLayer_khronos_validation.dylib	0x000000012220d4c9 PHYSICAL_DEVICE_STATE::GetQueueFamilyProps(VkPhysicalDevice_T*) + 57 (device_state.h:116)
2   libVkLayer_khronos_validation.dylib	0x000000012220d3fb PHYSICAL_DEVICE_STATE::PHYSICAL_DEVICE_STATE(VkPhysicalDevice_T*) + 75 (device_state.h:108)
3   libVkLayer_khronos_validation.dylib	0x000000012220d21d PHYSICAL_DEVICE_STATE::PHYSICAL_DEVICE_STATE(VkPhysicalDevice_T*) + 29 (device_state.h:108)
4   libVkLayer_khronos_validation.dylib	0x000000012220d186 std::__1::__shared_ptr_emplace<PHYSICAL_DEVICE_STATE, std::__1::allocator<PHYSICAL_DEVICE_STATE> >::__shared_ptr_emplace<VkPhysicalDevice_T*&>(std::__1::allocator<PHYSICAL_DEVICE_STATE>, VkPhysicalDevice_T*&) + 118 (memory:2627)
5   libVkLayer_khronos_validation.dylib	0x000000012220ce7d std::__1::__shared_ptr_emplace<PHYSICAL_DEVICE_STATE, std::__1::allocator<PHYSICAL_DEVICE_STATE> >::__shared_ptr_emplace<VkPhysicalDevice_T*&>(std::__1::allocator<PHYSICAL_DEVICE_STATE>, VkPhysicalDevice_T*&) + 29 (memory:2621)
6   libVkLayer_khronos_validation.dylib	0x000000012220cd71 std::__1::shared_ptr<PHYSICAL_DEVICE_STATE> std::__1::allocate_shared<PHYSICAL_DEVICE_STATE, std::__1::allocator<PHYSICAL_DEVICE_STATE>, VkPhysicalDevice_T*&, void>(std::__1::allocator<PHYSICAL_DEVICE_STATE> const&, VkPhysicalDevice_T*&) + 97 (memory:3385)
7   libVkLayer_khronos_validation.dylib	0x000000012219563d std::__1::shared_ptr<PHYSICAL_DEVICE_STATE> std::__1::make_shared<PHYSICAL_DEVICE_STATE, VkPhysicalDevice_T*&, void>(VkPhysicalDevice_T*&) + 61 (memory:3394)
8   libVkLayer_khronos_validation.dylib	0x00000001221955e7 ValidationStateTracker::CreatePhysicalDeviceState(VkPhysicalDevice_T*) + 39 (state_tracker.cpp:3293)
9   libVkLayer_khronos_validation.dylib	0x00000001221957ad ValidationStateTracker::PostCallRecordCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**, VkResult) + 349 (state_tracker.cpp:3316)
10  libVkLayer_khronos_validation.dylib	0x0000000121f2999f vulkan_layer_chassis::CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) + 3599 (chassis.cpp:362)
11  libvulkan.1.3.203.dylib       	0x000000010db93c42 loader_create_instance_chain + 2434 (loader.c:4948)
12  libvulkan.1.3.203.dylib       	0x000000010db9f379 vkCreateInstance + 1417 (trampoline.c:579)
13  com.lunarg.vkcube             	0x000000010db10949 demo_init_vk + 1801 (cube.c:3335)
14  com.lunarg.vkcube             	0x000000010db0f233 demo_init + 1619 (cube.c:4066)
15  com.lunarg.vkcube             	0x000000010db0e7b7 demo_main + 39 (cube.c:4173)
16  com.lunarg.vkcube             	0x000000010db0e6d4 -[DemoViewController viewDidLoad] + 404 (DemoViewController.m:59)

**Comment by richard-lunarg** [comment]
We are failing again on Apple Silicon as of 2/7/2022 

90% tests passed, 2 tests failed out of 20

Total Test time (real) =   1.11 sec

The following tests FAILED:
	 15 - VkLayer_tests (Failed)
	 17 - VkLayer_tests_mechanism (Failed)
Errors while running CTest
[LastTest.log](https://github.com/KhronosGroup/Vulkan-Profiles/files/8019240/LastTest.log)

**Comment by richard-lunarg** [comment]
All tests pass on all hardware! Woot, closing this issue!
