### ISSUE TITLE
VP_KHR_roadmap_2024 missing

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Profiles#603]
I was wondering why the recently announced VP_KHR_roadmap_2024 profile isn't available in the profiles library or the latest SDK.

The LunarG Vulkan Ecosystem Survey mentions it:

![image](https://github.com/KhronosGroup/Vulkan-Profiles/assets/10283127/ae527d28-a0c1-49bd-aec2-3b448f163b4f)

But afaik it's not yet available anywhere.

Or did I miss something?

**Comment by KarenGhavam-lunarG** [comment]
The 2024 roadmap profile was not released in time for the SDK. The release notes of the SDK indicate roadmap profiles are found in VP_KHR_roadmap.json

The 2024 roadmap profile is in VP_KHR_roadmap.json and will be in a future SDK.

**Comment by SaschaWillems** [comment]
Thanks for the quick response :)

Where do I find that file? It's not included in this repo.

**Comment by KarenGhavam-lunarG** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/tree/main/xml/profiles

It was decided a long time ago that roadmap profiles are kept in the xml directory

**Comment by SaschaWillems** [comment]
Thanks for that link. In my CapsViewer I'm using this library to read support for the different profiles, but even the latest commit here seems to only offer support for `VP_KHR_ROADMAP_2022` and not for `VP_KHR_ROADMAP_2024`. Or am I missing something?

**Comment by SaschaWillems** [comment]
Disregard my last comment. It seems I have to build this project to get an up-to-date version of the library, which includes the 2024 roadmap.

Is there a way we can get a pre-built version of the library outside of SDK releases? I once included a manually built one form this repo which had some profiles not meant for public use.

**Comment by SaschaWillems** [comment]
Pre-built as in using CI/CD to build from e.g. tags and automatically upload a "known good" version of the profiles library. I used to build it myself from this repo, but at some point that resulted in some non-finished/non-public profiles to get into the database. So I'm kinda reluctant to simply build from the latest commit.

One problem with SDK approach for ISV/IHVs are the release cycles. Roadmap 2024 has been announced, but there is no definitive way for me to get support for it into my caps viewer and the database until the next SDK release. It would be great if we could get proper support outside of the SDK and closer to actual release dates.

**Comment by christophe-lunarg** [comment]
A Roadmap 2024 tag works for me ! 

DONE : https://github.com/KhronosGroup/Vulkan-Profiles/tree/roadmap2024

**Comment by SaschaWillems** [comment]
Awesome. Thank you very much :)
