### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/Vulkan-Profiles#608]
`cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release -DUPDATE_DEPS=ON`

[log.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/14221292/log.txt)

**Comment by christophe-lunarg** [comment]
Hi!
I think your build failed because the repository dependences are not up to date. 
If you delete your build directory and use:
cmake -S . -B build/ -D CMAKE_BUILD_TYPE=Release -D UPDATE_DEPS=ON
That should fix it. I don't know how Ninja is working here.
