### ISSUE TITLE
Generated vulkan_profiles.hpp has unecessary warnings

### ISSUE THREAD

**Issue by Avokadoen** [KhronosGroup/Vulkan-Profiles#619]
The generated vulkan_profile.hpp headers has warnings that can be avoided. 

These warnings can cause issues as some projects utilize `-Wall -Werror`.
The warnings I am hitting are specifically tied to `-Wmissing-braces`, `-Wunused-variable`. 

Seems trivial to fix from a first glance:
```python
            if paramList:
                gen += '                case {0}: {{\n'.format(structDef.sType)
                gen += '                    {0}* {1} = static_cast<{0}*>(static_cast<void*>(p));\n'.format(structDef.name, varName)
                for params in paramList:
                    genAssign = func('                    ' + fmt, params[0], varName + params[1], params[2])
                    if genAssign != '':
                        hasData = True
                        gen += genAssign
                gen += '                } break;\n'
```
Third line in this block can be moved to right before the line that does  `gen += genAssign` except it is behind a check for "if entering current branch first time". That way we never declare the switch case local pointer variable if there is no fields to assign on the pointer. 

```python
     if not profile_value.multiple_variants:
                gen += '    static const VpVariantDesc mergedCapabilities[] = {\n'
                gen += ('        {0},\n').format(profile_value.merge_capabilities.blockName)
                gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.instanceExtensions, 'instanceExtensions')
                gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.deviceExtensions, 'deviceExtensions')
                gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.features, 'featureStructTypes')
                gen += '            featureDesc,\n'
                gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.properties, 'propertyStructTypes')
                gen += '            propertyDesc,\n'
                gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.queueFamiliesProperties, 'queueFamilyStructTypes')
                gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.queueFamiliesProperties, 'queueFamilyDesc')
                gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.formats, 'formatStructTypes')
                gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.formats, 'formatDesc')
                gen += '        chainerDesc,\n'
                gen += '    };\n\n'
```
The code above is missing object encapsulating curly brackets. Just adding a the additional opening curly bracket write to the second line, additional start of line spacing to all the in-between lines and a closing bracket to the second to last line should fix it. 

```python
             gen += '    static const VpCapabilitiesDesc capabilities[] = {\n'
             for capability_keys in profile_value.referencedCapabilities:
                 gen += ('        {0}::variantCount, {0}::variants,\n').format(self.get_blockName(capability_keys))
```
The format string in the for loop body is missing object encapsulating curly brackets. 

Other than that, there are also some spaces here and there that can be removed:
```python
 VPAPI_ATTR bool isMultiple(double source, double multiple) {
     double mod = std::fmod(source, multiple);
     return std::abs(mod) < 0.0001; 
#                                                    ^here
```

```python 
struct VpProfileDesc {
    VpProfileProperties             props;
    uint32_t                        minApiVersion;

    const detail::VpVariantDesc*    pMergedCapabilities;

# ^ here
``` 

```python
    result = detail::vpGetInstanceProfileSupportSingleProfile(api_version, supported_instance_extensions, pProfile, &supported, supported_blocks, unsupported_blocks);
    if (result != VK_SUCCESS) {
        *pSupported = supported;
        return result;
    }

#^ here
```

```python
              if (variant.property.pfnFiller == nullptr) continue;

#^here
``` 

```python
    void PushBack(VkBaseOutStructure* found) { 
#                                                                           ^here
```

**Comment by christophe-lunarg** [comment]
> The generated vulkan_profile.hpp headers has warnings that can be avoided.
> 
> These warnings can cause issues as some projects utilize `-Wall -Werror`. The warnings I am hitting are specifically tied to `-Wmissing-braces`, `-Wunused-variable`.
> 
> Seems trivial to fix from a first glance:
> 
> ```python
>             if paramList:
>                 gen += '                case {0}: {{\n'.format(structDef.sType)
>                 gen += '                    {0}* {1} = static_cast<{0}*>(static_cast<void*>(p));\n'.format(structDef.name, varName)
>                 for params in paramList:
>                     genAssign = func('                    ' + fmt, params[0], varName + params[1], params[2])
>                     if genAssign != '':
>                         hasData = True
>                         gen += genAssign
>                 gen += '                } break;\n'
> ```
> 
> Third line in this block can be moved to right before the line that does `gen += genAssign` except it is behind a check for "if entering current branch first time". That way we never declare the switch case local pointer variable if there is no fields to assign on the pointer.
> 
> ```python
>      if not profile_value.multiple_variants:
>                 gen += '    static const VpVariantDesc mergedCapabilities[] = {\n'
>                 gen += ('        {0},\n').format(profile_value.merge_capabilities.blockName)
>                 gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.instanceExtensions, 'instanceExtensions')
>                 gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.deviceExtensions, 'deviceExtensions')
>                 gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.features, 'featureStructTypes')
>                 gen += '            featureDesc,\n'
>                 gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.properties, 'propertyStructTypes')
>                 gen += '            propertyDesc,\n'
>                 gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.queueFamiliesProperties, 'queueFamilyStructTypes')
>                 gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.queueFamiliesProperties, 'queueFamilyDesc')
>                 gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.formats, 'formatStructTypes')
>                 gen += self.gen_dataArrayInfo(profile_value.merge_capabilities.formats, 'formatDesc')
>                 gen += '        chainerDesc,\n'
>                 gen += '    };\n\n'
> ```
> 
> The code above is missing object encapsulating curly brackets. Just adding a the additional opening curly bracket write to the second line, additional start of line spacing to all the in-between lines and a closing bracket to the second to last line should fix it.
> 
> ```python
>              gen += '    static const VpCapabilitiesDesc capabilities[] = {\n'
>              for capability_keys in profile_value.referencedCapabilities:
>                  gen += ('        {0}::variantCount, {0}::variants,\n').format(self.get_blockName(capability_keys))
> ```
> 
> The format string in the for loop body is missing object encapsulating curly brackets.
> 
> Other than that, there are also some spaces here and there that can be removed:
> 
> ```python
>  VPAPI_ATTR bool isMultiple(double source, double multiple) {
>      double mod = std::fmod(source, multiple);
>      return std::abs(mod) < 0.0001; 
> #                                                    ^here
> ```
> 
> ```python
> struct VpProfileDesc {
>     VpProfileProperties             props;
>     uint32_t                        minApiVersion;
> 
>     const detail::VpVariantDesc*    pMergedCapabilities;
> 
> # ^ here
> ```
> 
> ```python
>     result = detail::vpGetInstanceProfileSupportSingleProfile(api_version, supported_instance_extensions, pProfile, &supported, supported_blocks, unsupported_blocks);
>     if (result != VK_SUCCESS) {
>         *pSupported = supported;
>         return result;
>     }
> 
> #^ here
> ```
> 
> ```python
>               if (variant.property.pfnFiller == nullptr) continue;
> 
> #^here
> ```
> 
> ```python
>     void PushBack(VkBaseOutStructure* found) { 
> #                                                                           ^here
> ```

Hi !

I fixed the issues regarding the extra space but I wasn't able to understand exactly what are your suggestions from the `curly brackets`. Would you mind to copy the code with the requested changes so that I could compare it with the original code? Visual C++ and GCC have differences with curly brackets which are not obvious to catch :/

**Comment by Avokadoen** [comment]
Hi @christophe-lunarg 
Thanks for looking into this, and sorry for the late reply.

So for the unused variable issue I am suggesting something like the following:
```python
            if paramList:
                hasLocalCastPtr = False
                gen += '                case {0}: {{\n'.format(structDef.sType)
                for params in paramList:
                    genAssign = func('                    ' + fmt, params[0], varName + params[1], params[2])
                    if genAssign != '':
                        if hasLocalCastPtr == False: 
                            gen += '                    {0}* {1} = static_cast<{0}*>(static_cast<void*>(p));\n'.format(structDef.name, varName)
                            hasLocalCastPtr = True
                        hasData = True
                        gen += genAssign
                gen += '                } break;\n'
```
This way there is no local pointer if we are not setting the members of whatever is pointed at.

For the missing curly brackets:
```python
            if not profile_value.multiple_variants:
                gen += '    static const VpVariantDesc mergedCapabilities[] = {\n'
                gen += '        {\n'
                gen += '    ' + ('        {0},\n').format(profile_value.merge_capabilities.blockName)
                gen += '    ' + self.gen_dataArrayInfo(profile_value.merge_capabilities.instanceExtensions, 'instanceExtensions')
                gen += '    ' + self.gen_dataArrayInfo(profile_value.merge_capabilities.deviceExtensions, 'deviceExtensions')
                gen += '    ' + self.gen_dataArrayInfo(profile_value.merge_capabilities.features, 'featureStructTypes')
                gen += '    ' + '            featureDesc,\n'
                gen += '    ' + self.gen_dataArrayInfo(profile_value.merge_capabilities.properties, 'propertyStructTypes')
                gen += '    ' + '            propertyDesc,\n'
                gen += '    ' + self.gen_dataArrayInfo(profile_value.merge_capabilities.queueFamiliesProperties, 'queueFamilyStructTypes')
                gen += '    ' + self.gen_dataArrayInfo(profile_value.merge_capabilities.queueFamiliesProperties, 'queueFamilyDesc')
                gen += '    ' + self.gen_dataArrayInfo(profile_value.merge_capabilities.formats, 'formatStructTypes')
                gen += '    ' + self.gen_dataArrayInfo(profile_value.merge_capabilities.formats, 'formatDesc')
                gen += '    ' + '        chainerDesc,\n'
                gen += '        },\n'
                gen += '    };\n\n'
```
And
```python
            gen += '    static const VpCapabilitiesDesc capabilities[] = {\n'
            for capability_keys in profile_value.referencedCapabilities:
                gen += ('        {{ {0}::variantCount, {0}::variants }},\n').format(self.get_blockName(capability_keys))
            gen += '    };\n'
```
