### ISSUE TITLE
layer: List of extensions to modify extensions on top of the selected profile?

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-Profiles#62]
Potential new feature to the Profiles layer: adding a setting with a list of extensions that can be added and enabled.
This list of enabled/disabled extensions would override the extensions on top of the selected profile.

**Comment by bradgrantham-lunarg** [comment]
Here's a use case that is mostly straightforward with old DevSim.  If Profiles is to fully replace DevSim, it will need to handle this case.

I'm looking into a crash VK_ANDROID_external_memory_android_hardware_buffer.  It hooks Vulkan images and Android hardware buffers together (e.g. from the camera or from a decoded video).  We don't have that AHardwareBuffer* in replay.  We might be able to capture the image data in capture but it could be DRM, in which case we can't. One part of the solution is that we tell this company to try to capture games with the extension forced off.  (If that doesn't work, then we try to do something more clever like capturing the AHardwareBuffer characteristics and in replay provide an image of the same size with junk data like a checkerboard or Vulkan logo.)

Here's a DevSim JSON that blocks one extension (apologies to AMD, this is just the first extension MoltenVK reports on my Mac):
```
{
    "$schema": "https://schema.khronos.org/vulkan/devsim_1_0_0.json#",
    "ArrayOfVkExtensionProperties": [
{"extensionName" :"VK_AMD_gpu_shader_half_float", "specVersion": 1}
    ]
}
```

I ran vulkaninfo devsim like so:
```
VK_LUNARG_DEVICE_SIMULATION_FILENAME=/Users/grantham/tmp/blarg.json VK_DEVICE_SIMULATION_MODIFY_EXTENSION_LIST=blacklist  VK_LAYER_PATH=/Users/grantham/VulkanSDK/1.2.189.0/macOS/share/vulkan/explicit_layer.d VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_device_simulation vulkaninfo > ~/tmp/with_devsim.txt
```
And then again without devsim:
```
vulkaninfo > ~/tmp/without_devsim.txt
```
And the resulting output has had "VK_AMD_gpu_shader_half_float" removed:
```
$ diff ~/tmp/without_devsim.txt ~/tmp/with_devsim.txt
[...]
573c565
< Device Extensions: count = 54
---
> Device Extensions: count = 53
575d566
< VK_AMD_gpu_shader_half_float          : extension revision 2
[...]
```
