### ISSUE TITLE
minSubgroupSize/maxSubgroupSize not consistent

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-Profiles#633]
https://github.com/KhronosGroup/Vulkan-Profiles/commit/b03ca5ea078f9201efffcaf6369f04d884e57ce8 (from 
https://github.com/KhronosGroup/Vulkan-Profiles/pull/618)

changed 

```c++
-            self.structs['VkPhysicalDeviceVulkan13Properties'].members['minSubgroupSize'].limittype = 'min,pot'
-            self.structs['VkPhysicalDeviceVulkan13Properties'].members['maxSubgroupSize'].limittype = 'max,pot'
+           self.structs['VkPhysicalDeviceVulkan13Properties'].members['minSubgroupSize'].limittype = 'exact'
+           self.structs['VkPhysicalDeviceVulkan13Properties'].members['maxSubgroupSize'].limittype = 'exact'
```

which broke validation layers testing because now `maxSubgroupSize`/`minSubgroupSize` can not be modified (is this correct?)

another issue is these values are modified still when using `VkPhysicalDeviceSubgroupSizeControlProperties`/`VkPhysicalDeviceSubgroupSizeControlPropertiesEXT`

**Comment by christophe-lunarg** [comment]
Ohhh, these are annoying once... :/

I would rather go the route to also set as exact in `VkPhysicalDeviceSubgroupSizeControlProperties/EXT` for simplicity but I'll investigate, probably that wasn't the right fix...

**Comment by spencer-lunarg** [comment]
I don't know any context why you made the change, but the `vk.xml` doesn't have `exact` so not sure why profile would override it instead of just updating the `vk.xml` in the spec

**Comment by christophe-lunarg** [comment]
This is fixed in main branch, sorry about this, I think that was a mistake!

**Comment by spencer-lunarg** [comment]
its ok, basically the VVL uses the 1.3.278 tag for CI and I personally always try and grab latest.. basically catching this now is 1000 times better then when Mike tries to do a header update
