### ISSUE TITLE
Compiler warning about unreferenced formal parameter

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Profiles#645]
Using the profiles library adds a few new compiler warnings to my project in MSVC (~a dozen):

warning C4100: 'pAllocator': unreferenced formal parameter

This seems to be caused by [this function](https://github.com/KhronosGroup/Vulkan-Profiles/blob/9cb102135f5caa5af46c81ba1b6e983efed81e15/scripts/gen_profiles_solution.py#L1132) (and the one below). They both take a `pAllocator` argument that is never used.

**Comment by christophe-lunarg** [comment]
Hopefully this issue is resolved with https://github.com/KhronosGroup/Vulkan-Profiles/pull/646, sadly I am not seeing these warnings on my marchine despite using /Wall :/
