### ISSUE TITLE
Static function import breaks builds with VK_NO_PROTOTYPES

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Profiles#657]
After updating my Vulkan Hardware Capability Viewer to the latest version of the profiles, I'm no longer able to compile for Android.

The problem seems to be in how the profiles library now seems to import functions:

![image](https://github.com/KhronosGroup/Vulkan-Profiles/assets/10283127/56824afe-2c40-4331-9873-2ea70b6c8bf7)

For Android I'm loading functions dynamically and specify `VK_NO_PROTOTYPES`.  So the functions referenced in `ImportVulkanFunctions_Static` or obviously not defined, resulting in a build/link failure.

The profiles library should respect that define and shouldn't declare any static stuff when that define is present.

I also wonder why the `VP_PROFILE_CREATE_DYNAMIC_BIT` has been commented out.

🛑 This is kinda urgent for me, as it stops me from releasing a new caps viewer with recent  profiles support. For Android, the profiles library is not usable in it's current state for me.

**Comment by SaschaWillems** [comment]
This seems to have been a pretty recent changes. A few weeks ago the profiles library compiled fine for me on Android 😟

**Comment by SaschaWillems** [comment]
I'll probably do a hotfix locally, so I can release the version without waiting for a fix. Having an official fix would be appreciated though.

And maybe add a build to the CI that uses `VK_NO_PROTOTYPES `.

**Comment by SaschaWillems** [comment]
I actually wonder why this is now necessary at all? The profiles library worked without having to pass functions in before. Why does it need those functions to be set now?

**Comment by christophe-lunarg** [comment]
The new API was added because of a feature request to enable using Vulkan API function loaded externally. I'll investigate to accomodate both build mode...

**Comment by SaschaWillems** [comment]
I'm fine with any way as long is works on Android with `VK_NO_PROTOTYPES`. Maybe you can add a pre processor define to toggle between the old and new api?

**Comment by christophe-lunarg** [comment]
Hi Sascha,

Here is a generated version of the Vulkan API library where I tried to make the `VK_NO_PROTOTYPES ` works following how it's done with VMA but I have to admit I am very unsure about it...

Attached the release and debug files if you want to try.

**Comment by christophe-lunarg** [comment]
From our email discussion, I understand this issue can be close. This said, I realized that the library was using `vkGetPhysicalDeviceProperties` which could not be externally loaded and was missing from the previous changes. This fixes is in https://github.com/KhronosGroup/Vulkan-Profiles/pull/665.
