### ISSUE TITLE
hpp header almost unusable in common IDEs

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Profiles#658]
I'm having troubles actually doing anything wit the generated `vulkan_profiles.hpp` in my two main IDEs: Visual Studio 2022 and QT Creator. In MSVC jumping to the declarations pretty much never works, and in QT Creator trying to navigate inside the header makes the IDE come to a crawl. I fear that the header is getting too large for many IDEs to handle, similar to the hpp Vulkan headers.

This is a severe hindrance when trying to actually use the header. I'm updating the caps viewer to the most recent version and stuff like code completion or jump to declaration not working in e.g. MSVC makes it almost unusable for me.

Is there a way to get the profiles library in smaller and less verbose version? I don't need all of the capabilities, e.g. I don't create a device or instance in the caps viewer.

Tbh. it has become a real nuisance and has forced me to delay new versions of the caps viewer multiple times.

**Comment by christophe-lunarg** [comment]
Hi Sascha,

For a while I have been thinking about the relevance of shipping a generated vulkan_profiles.hpp from the profiles that ships with the SDK.

In a way, each application should generate it's own Vulkan Profiles API library.

No Vulkan application should create VkDevice and VkInstance instances from the Khronos Roadmap profiles or the Baseline profiles. Checking whether one of these profile is supported, maybe.

So maybe, some ideas:
- I should add a mode to generate Vulkan Profiles API libraries with only the hability to check profiles support (That would device the size by two)
- I should create a build of the library that only include the Roadmap profiles on desktop
- I should create a build of the library that only include the Roadmap profiles and the Android profiles on Android
- I should just remove the desktop baseline profiles from the library as really they are exemples for the Vulkan application to create their own and they aim to be used only as platform profile, so with the Vulkan Profiles layer.

Would you see it as an issue to call a python script (shipping with the SDK) with the selection of profile you wish to generate the vulkan_profiles.hpp for vulkancapsviewer?

**Comment by SaschaWillems** [comment]
> Would you see it as an issue to call a python script (shipping with the SDK) with the selection of profile you wish to generate the vulkan_profiles.hpp for vulkancapsviewer?

No problem I'm fine with that. I already do code gen (with php though), and adding another step shouldn't be a problem.

Thanks :)

**Comment by christophe-lunarg** [comment]
In https://github.com/KhronosGroup/Vulkan-Profiles/pull/665 I removed the desktop baseline profiles that took a lot of place. It's not an ideal fix and I don't know what an ideal fix could be but I think it will do for now.
