### ISSUE TITLE
vkconfig cannot successfully parse the profile layer manifest file

### ISSUE THREAD

**Issue by davidlunarg** [KhronosGroup/Vulkan-Profiles#67]
If I try to use vkconfig to view the layer documentation for the profile layer, vkconfig errors out when parsing the profiles layer manifest file (VkLayer_khronos_profiles.json).

If I remove the line "format": "PROFILE" from the manifest file, vkconfig can parse the file.

Not sure if this is a problem in vkconfig or the profile layer manifest.

**Comment by christophe-lunarg** [comment]
What version of vkconfig are you using?

**Comment by davidlunarg** [comment]
I haven't rebased my branch in quite a while. Will do that.

**Comment by davidlunarg** [comment]
The problem only occurs when I try to generate a doc file using the command line:

    vkconfig doc settings VK_LAYER_KHRONOS_profiles /tmp

It also occurs if I replace "settings" with "html" or "markdown" in the command above.

It does not happen if an html, settings, or markdown doc is generated from the vkconfig gui.

The version of vkconfig I am using is from branch davidlunarg/david_auto_doc_gen_rebase. I rebased to the latest master today.

I suspect this is a problem with vkconfig and am investigating further.

**Comment by davidlunarg** [comment]
The problem is in vkconfig - it fails when the json file refers to ${VULKAN_CONTENT}. I'll submit an issue in VulkanTools.
