### ISSUE TITLE
Schema: Improving the handling of feature/property synonyms

### ISSUE THREAD

**Issue by aqnuep** [KhronosGroup/Vulkan-Profiles#7]
There is an inherent limitation to the profiles solution, including the schema, layer, and library, stemming from the unfortunate choice made in the design of the Vulkan API whereas physical device features and properties in core API versions can be specified in two ways:

* First, in the feature/property structure inherited from the promoted extension (e.g. `robustImageAccess` field in the `VkPhysicalDeviceImageRobustnessFeatures` structure)
* Second, in the **aggregated** feature/property structure defined for the core API version (e.g. `robustImageAccess` field in the `VkPhysicalDeviceVulkan13Features` structure)

> **NOTE:** These types of synonyms are not the same as the ones inherent from the structure aliasing scheme (e.g. `VkPhysicalDeviceImageRobustnessFeature` defined in core vs `VkPhysicalDeviceImageRobustnessFeatureEXT` defined in `VK_EXT_image_robustness`).

This affects both the layer and the library in that if a profile defines `robustImageAccess` in `VkPhysicalDeviceVulkan13Features` then the feature will not be returned in `VkPhysicalDeviceImageRobustnessFeatures`, even though the two are synonyms of each other.

In addition, this could cause some obscure issues in the case of the library e.g. if the application provides `VkPhysicalDeviceImageRobustnessFeatures` in its `pNext` chain while the profile itself defines `VkPhysicalDeviceVulkan13Features`, as now we have two structures that both specify the same feature data.
The spec is actually under-defined in this respect, as while it doesn't allow specifying the same structure (even if they are aliases) twice in the same `pNext` chain, it does not disallow specifying two structures in the same `pNext` chain that may contain synonyms, like in the case of `VkPhysicalDeviceVulkan13Features` and `VkPhysicalDeviceImageRobustnessFeatures` in our example.

For return-only data, the only problem with this is the inconsistent data returned, as described above, and should be fixable by returning the data in either of the structures which contain a common synonym. However, this would require changes in both the layer and the library generator.

For input data, i.e. the structures passed to `vpCreateDevice` in the library, it may be possible to handle potential conflicts by always using one of the two possible synonyms (more specifically the non-`VkPhysicalDeviceVulkanXXFeatures` version of the structure containing the particular feature), however, implementing such a thing would require similar compromises as the currently unsupported "feature-merging" option, as it could only work with known structures, thus we could no longer support structures unknown to the library, except maybe at the end of the structure chain.

From the schema perspective, the problem is that there's no way to prevent using a JSON schema the possibility of specifying conflicting definitions of the same feature, e.g. `robustImageAccess` specified in both `VkPhysicalDeviceVulkan13Features` and `VkPhysicalDeviceImageRobustnessFeatures`. In fact, from the schema perspective, this issue is even there with regular alias structures, thus currently only the generator script is able to detect such conflicts.

Possible solution would thus involve changes to the layer and library to handle such synonyms, both in case of return structures and in input data to `vpCreateDevice` (with the caveats above).
At that point, however, the inherent question from the schema perspective is why we allow syntax to define potentially conflicting features/properties in the first place?
If we address this, hence, we can also think about whether it's worth simplifying the schema to not allow conflicting synonyms in the first place, by defining things per core version and/or extension instead of per struct as things are currently handled. In such a scheme a definition like the one below:
```
    "features": {
        "VkPhysicalDeviceVulkan13Features": {
            "robustImageAccess": true
        }
    }
    or
    "features": {
        "VkPhysicalDeviceImageRobustnessFeaturesEXT": {
            "robustImageAccess": true
        }
    }
```
... could be turned into something like this:
````
    "features": {
        "Vulkan 1.3": {
            "robustImageAccess": true
        }
    }
    or
    "features": {
        "VK_EXT_image_robustness": {
            "robustImageAccess": true
        }
    }
````
... as each extension only has at most one `VkPhysicalDeviceXXFeatures/PropertiesEXT/KHR/WHATEVER` structure whereas core versions always define two synonyms, one called `VkPhysicalDeviceXXFeatures/Properties` and the other (aggregating all core version specific structures) called `VkPhysicalDeviceVulkanXXFeatures/Properties`.

Thus the questions are:
* Do we want to resolve the current limitations around core feature/property structure synonyms stemming from the aggregated `VkPhysicalDeviceVulkanXXFeatures/Properties` structures?
* If yes, how? Are we okay with imposing limitations on accepting unknown structs?
* If yes, do we also want to simplify the schema so that there's no possibility to defined conflicting definitions?
* What about queue family/format/etc. structures?

From @ziga-lunarg:
> Note that currently in the layer, `VkPhysicalDeviceVulkan13Features` will take precedence over `VkPhysicalDeviceImageRobustnessFeatures` and any other such structs. 
Also a warning will be emitted by the layer for any such case.

Reply from @aqnuep:
> Yes, I'm aware of the warnings set up, but I'm less clear whether the current layer implementation will properly return information in e.g. `vkGetPhysicalDeviceFeatures2` for both structures, or only one of them.

**Comment by christophe-lunarg** [comment]
This is deferred for a future version 2.0
