### ISSUE TITLE
Inconsistant limittype specification

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Profiles#722]
Let us assume that if the limittype contains min for limit alpha then: `device->alpha >= limit->alpha` (similar holds for max)

As for:
- `minMemoryMapAlignment` is `min,pot` then `device->minMemoryMapAlignment >= limit`
- `minStorageBufferOffsetAlignment` is also `min,pot` so `device->minStorageBufferOffsetAlignment >= limit`

But as `minMemoryMapAlignment` restricts the device (the higher the limit the better), but `minStorageBufferOffsetAlignment` restricts the user (the lower the better) maybe (even if it sounds unintuitive) the limits that are restricting the user should have reversed limittypes.

Then we would have `minMemoryMapAlignment`: `min,pot`, but `minStorageBufferOffsetAlignment` would be `max,pot`, but that would align with the device/user restriction reasoning.

_Originally posted by @qbojj in https://github.com/KhronosGroup/Vulkan-Profiles/issues/703#issuecomment-2456966670_

**Comment by christophe-lunarg** [comment]
Hi,

If the problem is a `vk.xml` issue then I would suggest to report this issue here: https://github.com/KhronosGroup/Vulkan-Headers

Thanks
