### ISSUE TITLE
vk.xml: fixes and changes

### ISSUE THREAD

**Issue by aqnuep** [KhronosGroup/Vulkan-Profiles#8]
As lots of missing and incorrect information have been identified during the development of the generator script in the vk.xml, eventually those will need to get fixed in the vk.xml.
If needed, I can handle those once you feel that we should start working on it.

**Comment by christophe-lunarg** [comment]
- Some limit types are not correct:
  - subPixelPrecisionBits, subTexelPrecisionBits, mipmapPrecisionBits, viewportSubPixelBits, subPixelInterpolationOffsetBits, subgroupSize
- Some limit types could be more precisely specified (maxalign):
  - bufferImageGranularity, minMemoryMapAlignment, minTexelBufferOffsetAlignment, minUniformBufferOffsetAlignment, minStorageBufferOffsetAlignment, timestampPeriod, nonCoherentAtomSize, maxColorAttachments, pointSizeGranularity, lineWidthGranularity, minVertexInputBindingStrideAlignment
- Some limit types are set to bitmask but the type is VkBool32
- Some values are just missing limit types:
  - linearTilingFeatures, optimalTilingFeatures, bufferFeatures, queueCount, timestampValidBits, minImageTransferGranularity
- Some structures contains count + pointers to arrays
  - VkDrmFormatModifierPropertiesListEXT, VkDrmFormatModifierPropertiesList2EXT, VkVideoProfilesKHR

**Comment by christophe-lunarg** [comment]
minStorageBufferOffsetAlignment should be `minpot`

**Comment by christophe-lunarg** [comment]
bufferImageGranularity should be `min`

**Comment by christophe-lunarg** [comment]
subPixelPrecisionBits, subTexelPrecisionBits, mipmapPrecisionBits, viewportSubPixelBits, subPixelInterpolationOffsetBits should be `precisionbits` (or something)

**Comment by christophe-lunarg** [comment]
`subgroupSize` should be what ?

**Comment by christophe-lunarg** [comment]
`linearTilingFeatures`, 
`optimalTilingFeatures` and
`bufferFeatures` should be `bitmask`

**Comment by christophe-lunarg** [comment]
`queueCount`, should be what?

**Comment by christophe-lunarg** [comment]
`minSequencesCountBufferOffsetAlignment`
`minSequencesIndexBufferOffsetAlignment`
`minIndirectCommandsBufferOffsetAlignment` should be `min`

**Comment by christophe-lunarg** [comment]
`aspectMask` and `flags` is `VkSparseImageFormatProperties` are missing `bitmask`

**Comment by christophe-lunarg** [comment]
`maxTransformFeedbackBufferDataStride` should be `max`

**Comment by christophe-lunarg** [comment]
`shaderGroupHandleAlignment` should be `pot`

**Comment by christophe-lunarg** [comment]
maxSubpassShadingWorkgroupSizeAspectRatio should be `maxpot`

**Comment by christophe-lunarg** [comment]
`robustStorageBufferAccessSizeAlignment`
`robustUniformBufferAccessSizeAlignment` should be ???

**Comment by christophe-lunarg** [comment]
This was all done.
