### ISSUE TITLE
layer: Invalid warning shaderDrawParameters

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-Profiles#91]
I am getting an invalid warning as my GPU support `shaderDrawParameters` so something seem wrong:
```PROFILES WARNING: shaderDrawParameters JSON value is enabled in the profile, but the device does not support it.```

```
Launching Vulkan Application:
- Layers overridden by "New Configuration" configuration.
- Application: vkcube
- Executable: E:\VulkanSDK\1.3.204.0\Bin\vkcube.exe
- Working Directory: E:\VulkanSDK\1.3.204.0\Bin
- Command-line Arguments: --suppress_popups
- Log file: C:\Users\Piranha\VulkanSDK\vkcube.txt

LAYER SETTING (profile_name) error: The setting is used but the value is empty which is invalid for a string setting type.

PROFILES NOTIFICATION: Profile Layers Settings: {
	profile_file: E:\VulkanSDK\1.3.204.0\Config\VK_LAYER_KHRONOS_profiles\VP_LUNARG_desktop_portability_2021.json
	profile_name: 
	profile_validation: false
	emulate_portability: true
	simulate_capabilities: SIMULATE_API_VERSION_BIT, SIMULATE_FEATURES_BIT, SIMULATE_PROPERTIES_BIT
	debug_actions: DEBUG_ACTION_STDOUT_BIT
	debug_filename: profiles_layer_log.txt
	debug_file_clear: true
	debug_fail_on_error: false
	debug_reports: DEBUG_REPORT_NOTIFICATION_BIT, DEBUG_REPORT_WARNING_BIT, DEBUG_REPORT_ERROR_BIT
	exclude_device_extensions: 
	exclude_formats: 
}
```

**Comment by ziga-lunarg** [comment]
@christophe-lunarg Can you run vulkaninfo and attach the output?

**Comment by christophe-lunarg** [comment]
Does this count?
![image](https://user-images.githubusercontent.com/62888873/153016993-0663bbaa-8503-4d6c-8bd8-196c742a7c77.png)

**Comment by ziga-lunarg** [comment]
And it's the only gpu on the system?

**Comment by christophe-lunarg** [comment]
NVIDIA RTX

**Comment by ziga-lunarg** [comment]
Can you try to build from master and replace the lib in the SDK? I think this might be happening because #82 is not in the SDK yet.

**Comment by christophe-lunarg** [comment]
![profiles_draw_shader](https://user-images.githubusercontent.com/62888873/153021074-54651e6b-640a-48b9-924d-fdb199717a88.gif)
![rename](https://user-images.githubusercontent.com/62888873/153021077-7dd6ed79-3551-4c88-ac2e-e1f507422e7b.gif)

**Comment by christophe-lunarg** [comment]
I think you meant this issue https://github.com/KhronosGroup/Vulkan-Profiles/pull/86?

**Comment by christophe-lunarg** [comment]
I found somethings but that didn't resolve the issue... https://github.com/KhronosGroup/Vulkan-Profiles/pull/93
Very weird, I think I am missing something in my understanding of the system.

**Comment by christophe-lunarg** [comment]
So the issue is that the application Instance is created with VULKAN 1.0  so this:
```
                if (api_version_above_1_1) {
                    pdd.physical_device_protected_memory_properties_.pNext = property_chain.pNext;

                    property_chain.pNext = &(pdd.physical_device_protected_memory_properties_);

                    pdd.physical_device_protected_memory_features_.pNext = feature_chain.pNext;

                    pdd.physical_device_shader_draw_parameters_features_.pNext = &(pdd.physical_device_protected_memory_features_);

                    feature_chain.pNext = &(pdd.physical_device_shader_draw_parameters_features_);
                }
```
Isn't loaded.

**Comment by christophe-lunarg** [comment]
It's not clear to me how this issue should be handled from a Vulkan application developers perspective... 

Probably we need a WARNING when the Instance is created with a version of Vulkan lower than the profile that say that not all the profile will be applied.
