### ISSUE TITLE
Create a tool to combine multiple profiles

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-Profiles#95]
This would allow creating profile automatically

**Comment by per-mathisen-arm** [comment]
I already wrote such a tool in python. It is very hacky, though. What are the specific requirements here?

**Comment by null77** [comment]
This could be useful for ANGLE profile testing - maybe it's only well defined where there's an ordering to the layers, where later layers override the earlier ones?

**Comment by christophe-lunarg** [comment]
The script is now availlable in the repository!
Probably best to look at the unit tests `VpTestIntersect` and `VpTestUnion` to figure out how to use it.

I am still working on improvements and clean up.

Thanks
